[semver:patch]

diff --git a/src/commands/validate_documentation.yml b/src/commands/validate_documentation.yml
--- a/src/commands/validate_documentation.yml
+++ b/src/commands/validate_documentation.yml
@@ -7,11 +7,15 @@ steps:
         git submodule init
         git submodule update --remote --recursive
   - run:
-      name: Download pip
-      command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
-  - run:
-      name: Install pip
-      command: sudo python get-pip.py
+      name: Set Python
+      command: |
+        if ! pyenv -v COMMAND &> /dev/null
+        then
+            echo "pyenv could not be found"
+            exit
+        else
+            pyenv global 3.6.5
+        fi
   - run:
       name: Install virtualenv
       command: pip install --user virtualenv
